
source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'

def dev_pods
  pod 'SwiftLint', '= 0.42.0', configurations: ['Debug']
end

def core_pods

 pod 'RxSwift', '= 6.5.0'
 pod 'RxRelay', '= 6.5.0'
 pod 'Alamofire', '= 5.6.4'

end



target 'Moments' do
  use_frameworks!
  
  dev_pods
  core_pods
  
  

end
