
source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'

def core_pods

 pod 'RxSwift', '= 6.5.0'
 pod 'RxRelay', '= 6.5.0'
 pod 'Alamofire', '= 5.6.4'

end



target 'Moments' do
  use_frameworks!

  core_pods
  
  

end
